// <auto-generated />
namespace T5_Hospital.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Appointment_fk : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Appointment_fk));
        
        string IMigrationMetadata.Id
        {
            get { return "202207151558053_Appointment_fk"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
